Added AuthPage (#22)
* Update 9 files

* Update Registration.tsx and AuthPage.tsx

* fix webapp ci path

* Fix pipeline

* always run pipeline

* Fix script yml

* change brackets

* fix condition

* change pipeline config

* change error format

* change script

* fix eol

* change script

* test pipeline

* fix test pipeline

* fix i18next suspense

* Update 8 files

* Update 4 files

* Update 4 files

* Delete AuthPage.tsx

* Update auth.json

* Delete .LogIn.tsx.swp

* Update LogIn.tsx and Registration.tsx

* Update 6 files

* refactor

* add axios

* add vscode settings

* change package lock

* update lock

---------

Co-authored-by: Yaroslav Zaprudskii <y.zaprudskii@gmail.com>

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -16,7 +16,7 @@ jobs:
         with:
           filters: |
             webapp:
-              - '/src/WebApp/**'
+              - 'src/WebApp/**'
   webapp:
     if: needs.changes.outputs.webapp == 'true'
     needs: changes
@@ -24,11 +24,28 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
-      - name: Webapp CI
-        uses: ./.github/workflows/actions/webapp
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 18
+  
+      - name: Install dependencies
+        run: cd ./src/WebApp && npm install
+  
+      - name: Lint
+        run: cd ./src/WebApp && npm run lint
+  
+      - name: Build
+        run: cd ./src/WebApp && npm run build
   pipeline:
+    if: always()
     needs: [changes, webapp]
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+      - name: Webapp error
+        run: |
+          if [ "${{ needs.webapp.result }}" == "failure" ] || [ "${{ needs.webapp.result }}" == "cancelled" ]; then
+            echo "Webapp error"
+            exit 1
+          else
+            echo "Webapp pipeline passed"
+          fi
