change script

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -42,5 +42,10 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Webapp error
-        if:  ${{ needs.webapp.result }} == failure || ${{ needs.webapp.result }} == cancelled
-        run: exit 1
+        run: |
+          if [ "${{ needs.webapp.result }}" == "failure" ] || [ "${{ needs.webapp.result }}" == "cancelled" ]; then
+            echo "Webapp error"
+            exit 1
+          else
+            echo "Webapp pipeline passed"
+          fi
